plugin:
    name: 'mater.reservations::lang.plugin.name'
    description: 'mater.reservations::lang.plugin.description'
    author: 'Mateusz Rycombel'
    icon: icon-refresh
    homepage: ''
navigation:
    reservations:
        label: 'mater.reservations::lang.navigation.reservations.label'
        url: mater/reservations/clients
        icon: icon-refresh
        order: 700
        sideMenu:
            clients:
                label: 'mater.reservations::lang.navigation.client.label'
                url: mater/reservations/clients
                icon: icon-users
            reservations:
                label: 'mater.reservations::lang.navigation.reservation.label'
                url: mater/reservations/reservations
                icon: icon-ticket
            service_types:
                label: 'mater.reservations::lang.navigation.reservation.service_types'
                url: mater/reservations/servicetypes
                icon: icon-wrench
            employees:
                label: 'mater.reservations::lang.navigation.employees'
                url: mater/reservations/employees
                icon: icon-user