# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Service Type

# Model Form Field configuration
form: $/mater/reservations/models/servicetype/fields.yaml

# Model Class name
modelClass: Mater\Reservations\Models\ServiceType

# Default redirect location
defaultRedirect: mater/reservations/servicetypes

# Create page
create:
    title: backend::lang.form.create_title
    redirect: mater/reservations/servicetypes/update/:id
    redirectClose: mater/reservations/servicetypes

# Update page
update:
    title: backend::lang.form.update_title
    redirect: mater/reservations/servicetypes
    redirectClose: mater/reservations/servicetypes

# Preview page
preview:
    title: backend::lang.form.preview_title
